-- Pendientes operativos (inspirado en hoja PENDIENTES del Excel).

create table if not exists public.pendientes (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  descripcion text not null default '',
  estado text not null default 'ABIERTO',
  fecha date not null default (current_date),
  prioridad text not null default 'MEDIA',
  created_at timestamptz not null default now()
);

create index if not exists pendientes_empresa_id_idx on public.pendientes (empresa_id);
create index if not exists pendientes_empresa_fecha_idx on public.pendientes (empresa_id, fecha desc);

comment on table public.pendientes is 'Seguimiento de tareas pendientes por empresa / vehículo.';
comment on column public.pendientes.estado is 'ABIERTO | EN_CURSO | RESUELTO | CANCELADO';
comment on column public.pendientes.prioridad is 'ALTA | MEDIA | BAJA';
