-- Historial de cambios en préstamos financieros (registros desde la app u otros clientes).
-- SELECT: mismos roles que ven préstamos. INSERT: admin y contador (como edición de préstamos).

create table if not exists public.prestamo_financiero_historial (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  prestamo_financiero_id bigint not null references public.prestamos_financieros (id) on delete cascade,
  actor_id uuid,
  action text not null,
  summary text not null default '',
  details jsonb not null default '{}'::jsonb
);

create index if not exists prestamo_fin_hist_prestamo_created_idx
  on public.prestamo_financiero_historial (prestamo_financiero_id, created_at desc);

create index if not exists prestamo_fin_hist_empresa_idx
  on public.prestamo_financiero_historial (empresa_id);

comment on table public.prestamo_financiero_historial is
  'Historial de altas y ediciones de préstamos (payload en details).';

alter table public.prestamo_financiero_historial enable row level security;

drop policy if exists "prestamo_fin_hist_select_finanzas" on public.prestamo_financiero_historial;
create policy "prestamo_fin_hist_select_finanzas"
  on public.prestamo_financiero_historial for select
  to authenticated
  using (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador', 'operador')
    )
  );

drop policy if exists "prestamo_fin_hist_insert_finanzas" on public.prestamo_financiero_historial;
create policy "prestamo_fin_hist_insert_finanzas"
  on public.prestamo_financiero_historial for insert
  to authenticated
  with check (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'contador')
    )
  );
