-- Indisponibilidad operativa por vehículo (disponibilidad / pérdida de oportunidad).
-- No genera gastos ni modifica ingresos/utilidad.

create table if not exists public.vehicle_downtime (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint not null references public.vehiculos (id) on delete cascade,
  fecha_inicio date not null,
  fecha_fin date,
  motivo text not null,
  comentario text not null default '',
  estado text not null default 'activo',
  created_at timestamptz not null default now(),
  constraint vehicle_downtime_motivo_check check (
    motivo in (
      'taller',
      'multa',
      'mantenimiento',
      'accidente',
      'sin_conductor',
      'administrativo',
      'otro'
    )
  ),
  constraint vehicle_downtime_estado_check check (estado in ('activo', 'cerrado')),
  constraint vehicle_downtime_fechas_check check (
    fecha_fin is null or fecha_fin >= fecha_inicio
  )
);

create index if not exists vehicle_downtime_empresa_id_idx on public.vehicle_downtime (empresa_id);
create index if not exists vehicle_downtime_vehicle_id_idx on public.vehicle_downtime (vehicle_id);
create index if not exists vehicle_downtime_empresa_estado_idx on public.vehicle_downtime (empresa_id, estado);

comment on table public.vehicle_downtime is 'Registro de indisponibilidad operativa por vehículo; impacto económico se calcula en app (no persistido).';
comment on column public.vehicle_downtime.motivo is 'taller | multa | mantenimiento | accidente | sin_conductor | administrativo | otro';
comment on column public.vehicle_downtime.estado is 'activo | cerrado';

-- RLS (mismo patrón que kilometrajes)
create or replace function public.can_mutate_vehicle_downtime()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select
        coalesce(p.is_active, true)
        and lower(trim(p.role::text)) in ('admin', 'contador', 'socio')
        and not public.is_restricted_operador_account()
      from public.user_profiles p
      where p.id = auth.uid()
      limit 1
    ),
    false
  );
$$;

revoke all on function public.can_mutate_vehicle_downtime() from public;
grant execute on function public.can_mutate_vehicle_downtime() to authenticated;

do $$
declare pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'vehicle_downtime'
  loop
    execute format('drop policy if exists %I on public.vehicle_downtime', pol.policyname);
  end loop;
end $$;

alter table public.vehicle_downtime enable row level security;
alter table public.vehicle_downtime force row level security;

create policy "vehicle_downtime_select_tenant_active"
  on public.vehicle_downtime for select to authenticated
  using (public.is_active_user() = true and empresa_id = public.current_user_empresa_id());

create policy "vehicle_downtime_insert_tenant_editors"
  on public.vehicle_downtime for insert to authenticated
  with check (
    public.is_active_user() = true
    and public.can_mutate_vehicle_downtime() = true
    and empresa_id = public.current_user_empresa_id()
  );

create policy "vehicle_downtime_update_tenant_editors"
  on public.vehicle_downtime for update to authenticated
  using (
    public.is_active_user() = true
    and public.can_mutate_vehicle_downtime() = true
    and empresa_id = public.current_user_empresa_id()
  )
  with check (
    public.is_active_user() = true
    and public.can_mutate_vehicle_downtime() = true
    and empresa_id = public.current_user_empresa_id()
  );

create policy "vehicle_downtime_delete_tenant_editors"
  on public.vehicle_downtime for delete to authenticated
  using (
    public.is_active_user() = true
    and public.can_mutate_vehicle_downtime() = true
    and empresa_id = public.current_user_empresa_id()
  );

grant select, insert, update, delete on public.vehicle_downtime to authenticated;
