-- Caja negocio / utilidad por vehículo (antes mal clasificada en public.gastos).
-- Sin DROP. Revisar RLS (empresa_id) con el mismo criterio que ingresos/gastos.

create table if not exists public.caja_negocio_vehiculo (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint not null references public.vehiculos (id) on delete cascade,
  fecha date not null,
  monto numeric not null,
  concepto text not null default '',
  origen_gasto_id bigint,
  comentarios text not null default '',
  excel_extra jsonb,
  created_at timestamptz not null default now()
);

create index if not exists caja_negocio_vehiculo_empresa_id_idx
  on public.caja_negocio_vehiculo (empresa_id);
create index if not exists caja_negocio_vehiculo_vehicle_id_idx
  on public.caja_negocio_vehiculo (vehicle_id);
create index if not exists caja_negocio_vehiculo_fecha_idx
  on public.caja_negocio_vehiculo (fecha);
create index if not exists caja_negocio_vehiculo_origen_gasto_id_idx
  on public.caja_negocio_vehiculo (origen_gasto_id)
  where origen_gasto_id is not null;

comment on table public.caja_negocio_vehiculo is
  'Utilidad / caja generada por unidad; no es gasto operativo Fact ni ingreso de arriendo.';
comment on column public.caja_negocio_vehiculo.origen_gasto_id is
  'Id histórico del registro en public.gastos antes de moverlo (sin FK; la fila en gastos puede ya no existir).';
