-- Préstamos financieros informativos v2 (tasa anual, capital estimado, multi-moneda PEN/USD).
-- NO inserta gastos. Tras este DDL, ejecutar seed (migration_prestamos_financieros_seed_from_xlsx.sql)
-- o el archivo combinado migration_prestamos_financieros.sql.
-- Si la app no lista préstamos: supabase/diagnostico_prestamos_financieros.sql

drop table if exists public.prestamos_tramos cascade;
drop table if exists public.prestamos_financieros cascade;

create table public.prestamos_financieros (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  codigo text not null default '',
  prestamista text not null default '',
  moneda text not null default 'USD' check (moneda in ('PEN', 'USD')),
  monto_original numeric not null,
  capital_actual_estimado numeric not null,
  tasa_anual numeric not null,
  interes_mensual_actual numeric not null,
  fecha_inicio date not null,
  estado text not null default 'activo' check (estado in ('activo', 'cancelado')),
  fecha_cancelacion date,
  requiere_tramos boolean not null default false,
  notas text not null default '',
  created_at timestamptz not null default now()
);

create index prestamos_financieros_empresa_id_idx on public.prestamos_financieros (empresa_id);

create unique index prestamos_financieros_empresa_codigo_uidx
  on public.prestamos_financieros (empresa_id, codigo)
  where btrim(codigo) <> '';

comment on table public.prestamos_financieros is
  'Préstamo informativo: interés mensual ≈ capital_actual_estimado * tasa_anual / 12; sin movimientos en gastos.';
comment on column public.prestamos_financieros.tasa_anual is
  'Tasa nominal anual en decimal (ej. 0.12 = 12% anual pagado por meses).';
comment on column public.prestamos_financieros.interes_mensual_actual is
  'Cuota mensual vigente importada o alineada al Excel; la UI también muestra el valor derivado por fórmula.';

create table public.prestamos_tramos (
  id bigint generated by default as identity primary key,
  prestamo_financiero_id bigint not null references public.prestamos_financieros (id) on delete cascade,
  moneda text not null default 'USD' check (moneda in ('PEN', 'USD')),
  capital_referencial numeric,
  tasa_anual numeric not null,
  interes_mensual numeric,
  desde date not null,
  hasta date,
  evento text not null default '',
  nota text not null default '',
  orden smallint not null default 0,
  created_at timestamptz not null default now()
);

create index prestamos_tramos_prestamo_idx on public.prestamos_tramos (prestamo_financiero_id);

-- Un (prestamo, orden) por tramo; permite upsert idempotente en el seed.
create unique index if not exists prestamos_tramos_prestamo_orden_uidx
  on public.prestamos_tramos (prestamo_financiero_id, orden);

comment on table public.prestamos_tramos is
  'Tramos de capital/tasa/cuota; si interes_mensual es NULL se usa capital_referencial * tasa_anual / 12.';
comment on column public.prestamos_tramos.interes_mensual is
  'Cuota explícita del Excel; si NULL, derivada en la app con capital_referencial y tasa_anual.';

alter table public.prestamos_financieros enable row level security;
alter table public.prestamos_tramos enable row level security;

drop policy if exists "prestamos_financieros_select_finanzas" on public.prestamos_financieros;
create policy "prestamos_financieros_select_finanzas"
  on public.prestamos_financieros for select
  to authenticated
  using (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador', 'operador')
    )
  );

drop policy if exists "prestamos_tramos_select_finanzas" on public.prestamos_tramos;
create policy "prestamos_tramos_select_finanzas"
  on public.prestamos_tramos for select
  to authenticated
  using (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador', 'operador')
    )
  );
