-- Tablas control_fechas y kilometrajes (multi-tenant por empresa_id uuid).
-- Seguro sobre BD vacía o existente: CREATE IF NOT EXISTS + ADD COLUMN IF NOT EXISTS.
-- Sin DROP. Sin RLS aquí.
-- Requiere public.empresas(id uuid) y public.vehiculos(id) coherentes con vehicle_id.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- control_fechas (REG. FECHAS del Excel → app ControlFecha)
-- ---------------------------------------------------------------------------
create table if not exists public.control_fechas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  tipo text not null,
  fecha_vencimiento date not null,
  fecha_registro date not null,
  comentarios text not null default '',
  created_at timestamptz not null default now()
);

alter table public.control_fechas add column if not exists empresa_id uuid;
alter table public.control_fechas add column if not exists vehicle_id bigint;
alter table public.control_fechas add column if not exists tipo text not null default 'SOAT';
alter table public.control_fechas add column if not exists fecha_vencimiento date;
alter table public.control_fechas add column if not exists fecha_registro date;
alter table public.control_fechas add column if not exists comentarios text not null default '';
alter table public.control_fechas add column if not exists created_at timestamptz not null default now();

create index if not exists idx_control_fechas_empresa on public.control_fechas (empresa_id);
create index if not exists idx_control_fechas_vehicle on public.control_fechas (vehicle_id);

-- ---------------------------------------------------------------------------
-- kilometrajes (KMS del Excel → app KilometrajeRegistro)
-- ---------------------------------------------------------------------------
create table if not exists public.kilometrajes (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint not null references public.vehiculos (id) on delete cascade,
  fecha date not null,
  fecha_registro date not null,
  km_mantenimiento integer,
  kilometraje integer,
  descripcion text not null default '',
  costo numeric,
  created_at timestamptz not null default now()
);

alter table public.kilometrajes add column if not exists empresa_id uuid;
alter table public.kilometrajes add column if not exists vehicle_id bigint;
alter table public.kilometrajes add column if not exists fecha date;
alter table public.kilometrajes add column if not exists fecha_registro date;
alter table public.kilometrajes add column if not exists km_mantenimiento integer;
alter table public.kilometrajes add column if not exists kilometraje integer;
alter table public.kilometrajes add column if not exists descripcion text not null default '';
alter table public.kilometrajes add column if not exists costo numeric;
alter table public.kilometrajes add column if not exists created_at timestamptz not null default now();

create index if not exists idx_kilometrajes_empresa on public.kilometrajes (empresa_id);
create index if not exists idx_kilometrajes_vehicle_fecha on public.kilometrajes (vehicle_id, fecha desc);
