-- Propuesta: costos de inversión por vehículo (hoja VALOR DE INVERSION del Excel).
-- NO ejecutar en producción hasta revisar RLS y políticas.
-- Ajustar empresa_id / FK según tu modelo (uuid vs bigint).

create table if not exists public.inversiones_vehiculo (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  descripcion_excel text not null default '',
  fecha_compra date,
  valor_compra_usd numeric,
  gasto_gnv_usd numeric,
  gasto_notarial_usd numeric,
  leg_firmas_usd numeric,
  seguro_usd numeric,
  gps_usd numeric,
  fundas_accesorios_usd numeric,
  total_inversion_usd numeric,
  total_inversion_pen numeric,
  excel_extra jsonb,
  created_at timestamptz not null default now()
);

create index if not exists inversiones_vehiculo_empresa_id_idx on public.inversiones_vehiculo (empresa_id);
create index if not exists inversiones_vehiculo_vehicle_id_idx on public.inversiones_vehiculo (vehicle_id);
create index if not exists inversiones_vehiculo_fecha_compra_idx on public.inversiones_vehiculo (fecha_compra);

comment on table public.inversiones_vehiculo is 'Costos de inversión inicial por unidad (no gasto operativo mensual). Origen: Excel VALOR DE INVERSION.';
comment on column public.inversiones_vehiculo.descripcion_excel is 'Texto TIPO CARRO del Excel (p. ej. Yaris 01); vehicle_id puede resolverse por placa o N° interno en import.';
comment on column public.inversiones_vehiculo.excel_extra is 'Metadatos del parse (fila Excel, columnas crudas, etc.).';
