-- =============================================================================
-- Módulo Garantías — Fase 1 (aislado, no destructivo)
-- NO toca: ingresos, gastos, vehiculos, conductores, FKs existentes.
-- NO activa automatización de asignaciones.
-- =============================================================================

-- ── Parámetros de monto ─────────────────────────────────────────────────────
create table if not exists public.guarantee_settings (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_type text not null check (vehicle_type in ('auto', 'camioneta')),
  required_amount numeric(12, 2) not null check (required_amount >= 0),
  currency text not null default 'PEN',
  is_active boolean not null default true,
  updated_at timestamptz not null default now(),
  unique (empresa_id, vehicle_type)
);

comment on table public.guarantee_settings is
  'Montos de garantía requerida por tipo de vehículo (por empresa).';

-- ── Garantía principal (pertenece al conductor) ─────────────────────────────
create table if not exists public.driver_guarantees (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  driver_id text not null,
  current_vehicle_id bigint null references public.vehiculos (id) on delete set null,
  vehicle_type text not null check (vehicle_type in ('auto', 'camioneta')),
  required_amount numeric(12, 2) not null check (required_amount >= 0),
  -- Denormalizados (fuente de verdad = guarantee_movements; se recalculan al escribir)
  current_balance numeric(12, 2) not null default 0,
  total_contributed numeric(12, 2) not null default 0,
  total_deducted numeric(12, 2) not null default 0,
  status text not null default 'pendiente',
  closed_at timestamptz null,
  notes text null,
  created_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint driver_guarantees_status_chk check (
    status in (
      'sin_garantia',
      'pendiente',
      'completa',
      'incompleta',
      'con_descuentos_pendientes',
      'cerrada',
      'devuelta'
    )
  )
);

create unique index if not exists driver_guarantees_one_active_per_driver_uidx
  on public.driver_guarantees (empresa_id, driver_id)
  where closed_at is null and status not in ('cerrada', 'devuelta');

create index if not exists driver_guarantees_empresa_idx
  on public.driver_guarantees (empresa_id);

create index if not exists driver_guarantees_driver_idx
  on public.driver_guarantees (driver_id);

create index if not exists driver_guarantees_vehicle_idx
  on public.driver_guarantees (current_vehicle_id);

comment on table public.driver_guarantees is
  'Garantía del conductor (no del vehículo). Independiente de ingresos/gastos.';

-- ── Movimientos inmutables ──────────────────────────────────────────────────
create table if not exists public.guarantee_movements (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  guarantee_id bigint not null references public.driver_guarantees (id) on delete restrict,
  driver_id text not null,
  vehicle_id bigint null references public.vehiculos (id) on delete set null,
  movement_type text not null,
  amount numeric(12, 2) not null check (amount > 0),
  direction text not null check (direction in ('credit', 'debit')),
  observation text null,
  reason text null,
  related_movement_id bigint null references public.guarantee_movements (id) on delete set null,
  created_by uuid null,
  movement_date date not null default (timezone('America/Lima', now()))::date,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint guarantee_movements_type_chk check (
    movement_type in (
      'initial_deposit',
      'deposit',
      'fine_deduction',
      'damage_deduction',
      'repair_deduction',
      'other_deduction',
      'replenishment',
      'adjustment_credit',
      'adjustment_debit',
      'final_refund',
      'required_amount_change'
    )
  )
);

create index if not exists guarantee_movements_guarantee_created_idx
  on public.guarantee_movements (guarantee_id, created_at desc);

create index if not exists guarantee_movements_empresa_idx
  on public.guarantee_movements (empresa_id);

create index if not exists guarantee_movements_driver_idx
  on public.guarantee_movements (driver_id);

comment on table public.guarantee_movements is
  'Historial inmutable de garantías. Sin DELETE desde la app; correcciones vía ajuste.';

-- ── Asignaciones (preparado Fase 2; sin triggers) ───────────────────────────
create table if not exists public.vehicle_driver_assignments (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint not null references public.vehiculos (id) on delete cascade,
  driver_id text not null,
  start_date date not null default (timezone('America/Lima', now()))::date,
  end_date date null,
  is_active boolean not null default true,
  created_by uuid null,
  created_at timestamptz not null default now(),
  notes text null
);

create index if not exists vehicle_driver_assignments_active_idx
  on public.vehicle_driver_assignments (empresa_id, is_active)
  where is_active = true;

create index if not exists vehicle_driver_assignments_driver_idx
  on public.vehicle_driver_assignments (driver_id);

comment on table public.vehicle_driver_assignments is
  'Historial de asignaciones conductor↔vehículo. Fase 1: sin automatización. Fase 2: conectar fleetAssignmentService.';

-- ── Seed montos (todas las empresas existentes) ──────────────────────────────
insert into public.guarantee_settings (empresa_id, vehicle_type, required_amount)
select e.id, v.vehicle_type, v.required_amount
from public.empresas e
cross join (
  values
    ('auto'::text, 1000::numeric),
    ('camioneta'::text, 1500::numeric)
) as v(vehicle_type, required_amount)
on conflict (empresa_id, vehicle_type) do nothing;

-- ── RLS ─────────────────────────────────────────────────────────────────────
alter table public.guarantee_settings enable row level security;
alter table public.driver_guarantees enable row level security;
alter table public.guarantee_movements enable row level security;
alter table public.vehicle_driver_assignments enable row level security;

-- Lectura: admin / socio / contador activos (mismo tenant vía empresa_id en app)
drop policy if exists "guarantee_settings_select" on public.guarantee_settings;
create policy "guarantee_settings_select"
  on public.guarantee_settings for select to authenticated
  using (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador')
        and (p.empresa_id is null or p.empresa_id = guarantee_settings.empresa_id)
    )
  );

drop policy if exists "guarantee_settings_write" on public.guarantee_settings;
create policy "guarantee_settings_write"
  on public.guarantee_settings for all to authenticated
  using (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'contador')
        and (p.empresa_id is null or p.empresa_id = guarantee_settings.empresa_id)
    )
  )
  with check (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'contador')
        and (p.empresa_id is null or p.empresa_id = guarantee_settings.empresa_id)
    )
  );

drop policy if exists "driver_guarantees_select" on public.driver_guarantees;
create policy "driver_guarantees_select"
  on public.driver_guarantees for select to authenticated
  using (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador')
        and (p.empresa_id is null or p.empresa_id = driver_guarantees.empresa_id)
    )
  );

drop policy if exists "driver_guarantees_insert" on public.driver_guarantees;
create policy "driver_guarantees_insert"
  on public.driver_guarantees for insert to authenticated
  with check (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador')
        and (p.empresa_id is null or p.empresa_id = driver_guarantees.empresa_id)
    )
  );

drop policy if exists "driver_guarantees_update" on public.driver_guarantees;
create policy "driver_guarantees_update"
  on public.driver_guarantees for update to authenticated
  using (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador')
        and (p.empresa_id is null or p.empresa_id = driver_guarantees.empresa_id)
    )
  )
  with check (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador')
        and (p.empresa_id is null or p.empresa_id = driver_guarantees.empresa_id)
    )
  );

-- Sin DELETE de garantías desde clientes autenticados (cerrar vía status)
drop policy if exists "driver_guarantees_no_delete" on public.driver_guarantees;
-- (ausencia de policy DELETE = denegado con RLS)

drop policy if exists "guarantee_movements_select" on public.guarantee_movements;
create policy "guarantee_movements_select"
  on public.guarantee_movements for select to authenticated
  using (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador')
        and (p.empresa_id is null or p.empresa_id = guarantee_movements.empresa_id)
    )
  );

-- INSERT movimientos: admin/contador (descuentos, ajustes, devoluciones);
-- socio puede abonos/depósitos (tipos no sensibles se validan también en app)
drop policy if exists "guarantee_movements_insert" on public.guarantee_movements;
create policy "guarantee_movements_insert"
  on public.guarantee_movements for insert to authenticated
  with check (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador')
        and (p.empresa_id is null or p.empresa_id = guarantee_movements.empresa_id)
    )
  );

-- Sin UPDATE/DELETE de movimientos (inmutabilidad)
-- (ausencia de policies = denegado)

drop policy if exists "vehicle_driver_assignments_select" on public.vehicle_driver_assignments;
create policy "vehicle_driver_assignments_select"
  on public.vehicle_driver_assignments for select to authenticated
  using (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'socio', 'contador')
        and (p.empresa_id is null or p.empresa_id = vehicle_driver_assignments.empresa_id)
    )
  );

drop policy if exists "vehicle_driver_assignments_write" on public.vehicle_driver_assignments;
create policy "vehicle_driver_assignments_write"
  on public.vehicle_driver_assignments for all to authenticated
  using (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'contador')
        and (p.empresa_id is null or p.empresa_id = vehicle_driver_assignments.empresa_id)
    )
  )
  with check (
    exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid()
        and coalesce(p.is_active, true)
        and p.role in ('admin', 'contador')
        and (p.empresa_id is null or p.empresa_id = vehicle_driver_assignments.empresa_id)
    )
  );

grant select, insert, update on public.guarantee_settings to authenticated;
grant select, insert, update on public.driver_guarantees to authenticated;
grant select, insert on public.guarantee_movements to authenticated;
grant select, insert, update on public.vehicle_driver_assignments to authenticated;
