-- Hoja TIEMPO del Excel (SYSTEM): seguimiento operativo por vehículo (valor tiempo, taller, etc.)

create table if not exists public.registros_tiempo (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  fecha_registro timestamptz not null default now(),
  fecha date not null default (current_date),
  detalle_auto text,
  tipo text,
  descripcion text,
  valor_tiempo numeric,
  created_at timestamptz not null default now()
);

create index if not exists registros_tiempo_empresa_id_idx on public.registros_tiempo (empresa_id);
create index if not exists registros_tiempo_empresa_fecha_idx on public.registros_tiempo (empresa_id, fecha desc);
create index if not exists registros_tiempo_vehicle_id_idx on public.registros_tiempo (vehicle_id);

comment on table public.registros_tiempo is 'Equivalente a la hoja TIEMPO del Excel (F.REGISTRO, FECHA, N° carro, detalle, tipo, descripción, valor tiempo).';
comment on column public.registros_tiempo.fecha_registro is 'Momento en que se cargó el registro (columna F.REGISTRO del Excel).';
comment on column public.registros_tiempo.fecha is 'Fecha del hecho operativo (columna FECHA).';
comment on column public.registros_tiempo.valor_tiempo is 'Métrica numérica libre (horas, soles u otro criterio de negocio).';
