-- Gastos de caja del Excel (hoja GASTOS): no son gastos operativos por vehículo.
-- Revisar políticas RLS según el mismo criterio que ingresos/gastos (empresa_id).

create table if not exists public.gastos_caja (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  fecha date not null,
  concepto text not null default '',
  monto numeric not null,
  categoria text not null default 'CAJA_GENERAL',
  comentarios text not null default '',
  excel_extra jsonb,
  created_at timestamptz not null default now()
);

create index if not exists gastos_caja_empresa_id_idx on public.gastos_caja (empresa_id);
create index if not exists gastos_caja_fecha_idx on public.gastos_caja (fecha);
create index if not exists gastos_caja_categoria_idx on public.gastos_caja (categoria);

comment on table public.gastos_caja is 'Gastos de caja generales (Excel GASTOS E INGRESOS, hoja GASTOS). Separado de public.gastos (operativo por vehículo).';
comment on column public.gastos_caja.concepto is 'Texto principal (observación del Excel).';
comment on column public.gastos_caja.categoria is 'Clasificación interna; import usa CAJA_GENERAL si no hay subtipo en Excel.';
comment on column public.gastos_caja.excel_extra is 'Metadatos: fila Excel, fuente, etc.';
