-- migration_safe_alter.sql
-- Alinea tablas existentes con schema_reference.sql SIN borrar datos.
-- Reglas: sin DROP TABLE, sin DROP COLUMN, solo ADD COLUMN IF NOT EXISTS.
-- empresa_id permanece uuid. RLS no se toca aquí.
--
-- AVISOS MANUALES (revisar antes / después de ejecutar):
-- 1) Si una columna homónima ya existe con tipo incompatible (p. ej. fecha como text,
--    monto como double precision vs numeric, vehicle_id integer vs bigint), esta
--    migración NO la cambia: debes ALTER COLUMN ... TYPE ... USING ... en un script aparte.
-- 2) ADD COLUMN ... NOT NULL sin DEFAULT falla si la tabla tiene filas: aquí se usan
--    DEFAULTs seguros o columnas nullable donde hace falta; luego puedes endurecer NOT NULL.
-- 3) Columnas nuevas nullable (p. ej. empresa_id, fecha en tablas con datos): las filas
--    existentes quedan NULL hasta que ejecutes UPDATE; luego aplica NOT NULL si lo necesitas.
-- 4) Si tus tablas antiguas usan camelCase (vehicleId, fechaRegistro), los nombres no
--    coinciden con la app: renombra o crea vistas/columnas generadas aparte; este script
--    solo añade nombres snake_case del schema_reference.
-- 5) Claves foráneas nuevas no se añaden (riesgo con datos huérfanos). Tras validar
--    vehicle_id y empresa_id, crea FKs en otro paso.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- vehiculos (crear solo si no existe; si ya existe incompleta, aplican los ALTER)
-- ---------------------------------------------------------------------------
create table if not exists public.vehiculos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  marca text not null default '',
  modelo text not null default '',
  placa text not null default '',
  anio integer,
  color text,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.vehiculos add column if not exists empresa_id uuid;
alter table public.vehiculos add column if not exists marca text not null default '';
alter table public.vehiculos add column if not exists modelo text not null default '';
alter table public.vehiculos add column if not exists placa text not null default '';
alter table public.vehiculos add column if not exists anio integer;
alter table public.vehiculos add column if not exists color text;
alter table public.vehiculos add column if not exists activo boolean not null default true;
alter table public.vehiculos add column if not exists created_at timestamptz not null default now();

-- Si vehiculos se creó vacío sin FK: la fila de CREATE ya referencia empresas.
-- Si empresa_id quedó duplicada por ADD tras CREATE, en PG no duplica; IF NOT EXISTS evita.

-- ---------------------------------------------------------------------------
-- unidades
-- ---------------------------------------------------------------------------
alter table public.unidades add column if not exists empresa_id uuid;
alter table public.unidades add column if not exists vehicle_id bigint;
alter table public.unidades add column if not exists numero_interno text not null default '';
alter table public.unidades add column if not exists marca text not null default '';
alter table public.unidades add column if not exists modelo text not null default '';
alter table public.unidades add column if not exists anio integer not null default 0;
alter table public.unidades add column if not exists placa text not null default '';
alter table public.unidades add column if not exists detalle_auto text not null default '';
alter table public.unidades add column if not exists combustible text not null default '';
alter table public.unidades add column if not exists color text not null default '';
alter table public.unidades add column if not exists tipo_carroceria text;
alter table public.unidades add column if not exists numero_motor text;
alter table public.unidades add column if not exists cantidad_llaves integer;
alter table public.unidades add column if not exists gps1 text;
alter table public.unidades add column if not exists gps2 text;
alter table public.unidades add column if not exists impuesto_estado text;
alter table public.unidades add column if not exists km_inicial numeric;
alter table public.unidades add column if not exists tarjeta_propiedad text;
alter table public.unidades add column if not exists propietario text;
alter table public.unidades add column if not exists fecha_compra_usd date;
alter table public.unidades add column if not exists valor_compra_usd numeric;
alter table public.unidades add column if not exists tipo_cambio_compra numeric;
alter table public.unidades add column if not exists gasto_gnv text;
alter table public.unidades add column if not exists gastos_notariales text;
alter table public.unidades add column if not exists gastos_accesorios text;
alter table public.unidades add column if not exists gps_instalado boolean not null default false;
alter table public.unidades add column if not exists gps_proveedor text not null default '';
alter table public.unidades add column if not exists impuesto_vehicular_vence date;
alter table public.unidades add column if not exists comentarios text not null default '';
alter table public.unidades add column if not exists created_at timestamptz not null default now();

-- ---------------------------------------------------------------------------
-- conductores
-- ---------------------------------------------------------------------------
alter table public.conductores add column if not exists empresa_id uuid;
alter table public.conductores add column if not exists vehicle_id bigint;
alter table public.conductores add column if not exists tipo_documento text not null default 'DNI';
alter table public.conductores add column if not exists numero_documento text not null default '';
alter table public.conductores add column if not exists nombres text not null default '';
alter table public.conductores add column if not exists apellidos text not null default '';
alter table public.conductores add column if not exists celular text not null default '';
alter table public.conductores add column if not exists domicilio text not null default 'PROPIO';
alter table public.conductores add column if not exists estado_contrato text not null default 'ABIERTO';
alter table public.conductores add column if not exists estado text not null default 'VIGENTE';
alter table public.conductores add column if not exists status_original text;
alter table public.conductores add column if not exists cochera text;
alter table public.conductores add column if not exists numero_emergencia text;
alter table public.conductores add column if not exists direccion text;
alter table public.conductores add column if not exists documento_firmado boolean;
alter table public.conductores add column if not exists fecha_vencimiento_contrato date;
alter table public.conductores add column if not exists comentarios text not null default '';
alter table public.conductores add column if not exists created_at timestamptz not null default now();

-- ---------------------------------------------------------------------------
-- ingresos
-- NOTA: schema_reference usa vehicle_id NOT NULL; si tus filas antiguas tienen null,
-- no fuerces NOT NULL aquí. Tras limpiar datos: ALTER COLUMN vehicle_id SET NOT NULL.
-- ---------------------------------------------------------------------------
alter table public.ingresos add column if not exists empresa_id uuid;
alter table public.ingresos add column if not exists fecha date;
alter table public.ingresos add column if not exists fecha_registro date;
alter table public.ingresos add column if not exists vehicle_id bigint;
alter table public.ingresos add column if not exists tipo text not null default '';
alter table public.ingresos add column if not exists sub_tipo text;
alter table public.ingresos add column if not exists fecha_desde date;
alter table public.ingresos add column if not exists fecha_hasta date;
alter table public.ingresos add column if not exists metodo_pago text not null default '';
alter table public.ingresos add column if not exists metodo_pago_detalle text not null default '';
alter table public.ingresos add column if not exists celular_metodo text;
alter table public.ingresos add column if not exists signo text not null default '+';
alter table public.ingresos add column if not exists monto numeric not null default 0;
alter table public.ingresos add column if not exists moneda text not null default 'PEN';
alter table public.ingresos add column if not exists tipo_cambio numeric;
alter table public.ingresos add column if not exists monto_pen_referencia numeric;
alter table public.ingresos add column if not exists comentarios text not null default '';
alter table public.ingresos add column if not exists created_at timestamptz not null default now();
alter table public.ingresos add column if not exists detalle_operativo text;
alter table public.ingresos add column if not exists tipo_operacion text;
alter table public.ingresos add column if not exists estado_pago text;
alter table public.ingresos add column if not exists excel_extra jsonb;

-- ---------------------------------------------------------------------------
-- gastos
-- ---------------------------------------------------------------------------
alter table public.gastos add column if not exists empresa_id uuid;
alter table public.gastos add column if not exists fecha date;
alter table public.gastos add column if not exists fecha_registro date;
alter table public.gastos add column if not exists vehicle_id bigint;
alter table public.gastos add column if not exists tipo text not null default '';
alter table public.gastos add column if not exists sub_tipo text;
alter table public.gastos add column if not exists fecha_desde date;
alter table public.gastos add column if not exists fecha_hasta date;
alter table public.gastos add column if not exists metodo_pago text not null default '';
alter table public.gastos add column if not exists metodo_pago_detalle text not null default '';
alter table public.gastos add column if not exists celular_metodo text;
alter table public.gastos add column if not exists categoria text not null default 'OTROS';
alter table public.gastos add column if not exists motivo text not null default '';
alter table public.gastos add column if not exists signo text not null default '-';
alter table public.gastos add column if not exists monto numeric not null default 0;
alter table public.gastos add column if not exists pagado_a text not null default '';
alter table public.gastos add column if not exists comentarios text not null default '';
alter table public.gastos add column if not exists created_at timestamptz not null default now();
alter table public.gastos add column if not exists detalle_operativo text;
alter table public.gastos add column if not exists categoria_real text;
alter table public.gastos add column if not exists subcategoria text;
alter table public.gastos add column if not exists excel_extra jsonb;

-- ---------------------------------------------------------------------------
-- pendientes (nueva tabla)
-- ---------------------------------------------------------------------------
create table if not exists public.pendientes (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  descripcion text not null default '',
  estado text not null default 'ABIERTO',
  fecha date not null default (current_date),
  prioridad text not null default 'MEDIA',
  created_at timestamptz not null default now()
);

create index if not exists pendientes_empresa_id_idx on public.pendientes (empresa_id);
create index if not exists pendientes_empresa_fecha_idx on public.pendientes (empresa_id, fecha desc);

-- ---------------------------------------------------------------------------
-- registros_tiempo (hoja TIEMPO Excel)
-- ---------------------------------------------------------------------------
create table if not exists public.registros_tiempo (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  fecha_registro timestamptz not null default now(),
  fecha date not null default (current_date),
  detalle_auto text,
  tipo text,
  descripcion text,
  valor_tiempo numeric,
  created_at timestamptz not null default now()
);

create index if not exists registros_tiempo_empresa_id_idx on public.registros_tiempo (empresa_id);
create index if not exists registros_tiempo_empresa_fecha_idx on public.registros_tiempo (empresa_id, fecha desc);
create index if not exists registros_tiempo_vehicle_id_idx on public.registros_tiempo (vehicle_id);

-- ---------------------------------------------------------------------------
-- Comentarios de compatibilidad (metadatos en catálogo; no cambian tipos)
-- ---------------------------------------------------------------------------
comment on column public.ingresos.vehicle_id is
  'Si la columna ya existía como integer, Postgres no añade bigint duplicado; INCOMPATIBLE: convierte con ALTER COLUMN vehicle_id TYPE bigint USING vehicle_id::bigint.';

comment on column public.ingresos.monto is
  'Si monto era double precision/real, INCOMPATIBLE con numeric sin conversión explícita; usar ALTER ... TYPE numeric USING ...';

comment on column public.ingresos.fecha is
  'Si fecha era text/timestamptz, INCOMPATIBLE con date; normalizar con USING (fecha::date) o similar.';

comment on column public.gastos.monto is
  'Misma nota que ingresos.monto si el tipo previo no era numeric.';

comment on column public.unidades.empresa_id is
  'Si empresa_id existía como text o bigint, INCOMPATIBLE con uuid; migrar con USING y asegurar correspondencia con empresas.id.';
