-- Referencia para alinear Postgres con `src/services/*` y `supabaseMappers.ts`.
-- Ajusta tipos de `empresa_id` (uuid, bigint, text) y FK a `empresas` según tu modelo real.
-- RLS en Supabase debe acotar lectura/escritura al `empresa_id` del JWT o del cliente.

create extension if not exists "pgcrypto";

-- Ejemplo: empresa_id uuid referenciando empresas(id)
create table if not exists public.vehiculos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  marca text not null default '',
  modelo text not null default '',
  placa text not null default '',
  anio integer,
  color text,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.unidades (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  numero_interno text not null default '',
  marca text not null default '',
  modelo text not null default '',
  anio integer not null default 0,
  placa text not null default '',
  detalle_auto text not null default '',
  combustible text not null default '',
  color text not null default '',
  tipo_carroceria text,
  numero_motor text,
  cantidad_llaves integer,
  gps1 text,
  gps2 text,
  impuesto_estado text,
  km_inicial numeric,
  tarjeta_propiedad text,
  propietario text,
  fecha_compra_usd date,
  valor_compra_usd numeric,
  tipo_cambio_compra numeric,
  gasto_gnv text,
  gastos_notariales text,
  gastos_accesorios text,
  gps_instalado boolean not null default false,
  gps_proveedor text not null default '',
  impuesto_vehicular_vence date,
  comentarios text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.conductores (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  tipo_documento text not null,
  numero_documento text not null default '',
  nombres text not null default '',
  apellidos text not null default '',
  celular text not null default '',
  domicilio text not null,
  estado_contrato text not null,
  estado text not null,
  status_original text,
  cochera text,
  numero_emergencia text,
  direccion text,
  documento_firmado boolean,
  fecha_vencimiento_contrato date,
  comentarios text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.ingresos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  fecha date not null,
  fecha_registro date not null,
  vehicle_id bigint not null references public.vehiculos (id) on delete restrict,
  tipo text not null,
  sub_tipo text,
  fecha_desde date,
  fecha_hasta date,
  metodo_pago text not null,
  metodo_pago_detalle text not null,
  celular_metodo text,
  signo text not null default '+',
  monto numeric not null,
  moneda text not null default 'PEN',
  tipo_cambio numeric,
  monto_pen_referencia numeric,
  comentarios text not null default '',
  detalle_operativo text,
  tipo_operacion text,
  estado_pago text,
  excel_extra jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.gastos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  fecha date not null,
  fecha_registro date not null,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  tipo text not null,
  sub_tipo text,
  fecha_desde date,
  fecha_hasta date,
  metodo_pago text not null,
  metodo_pago_detalle text not null,
  celular_metodo text,
  categoria text not null,
  motivo text not null,
  signo text not null default '-',
  monto numeric not null,
  pagado_a text not null default '',
  comentarios text not null default '',
  detalle_operativo text,
  categoria_real text,
  subcategoria text,
  excel_extra jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.control_fechas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  tipo text not null,
  fecha_vencimiento date not null,
  fecha_registro date not null,
  comentarios text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.kilometrajes (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint not null references public.vehiculos (id) on delete cascade,
  fecha date not null,
  fecha_registro date not null,
  km_mantenimiento integer,
  kilometraje integer,
  descripcion text not null default '',
  costo numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.pendientes (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  descripcion text not null default '',
  estado text not null default 'ABIERTO',
  fecha date not null default (current_date),
  prioridad text not null default 'MEDIA',
  created_at timestamptz not null default now()
);

create table if not exists public.registros_tiempo (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references public.empresas (id) on delete cascade,
  vehicle_id bigint references public.vehiculos (id) on delete set null,
  fecha_registro timestamptz not null default now(),
  fecha date not null default (current_date),
  detalle_auto text,
  tipo text,
  descripcion text,
  valor_tiempo numeric,
  created_at timestamptz not null default now()
);
